# docker-compose.yml

version: '3.7'

networks:
  capri-network:
    driver: bridge

services:
  php:
    # Configurazione per il container Symfony/PHP
    build: infra/docker/php-8.2.18
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mysql
    networks:
      - capri-network

  mysql:
    # Configurazione per il container MySQL
    image: 'mysql:8.0.35'
    restart: always
    volumes:
      - ./infra/volumes/mysql_data:/var/lib/mysql
    command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=TheMovieDB
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
    networks:
      - capri-network

  nginx:
    # Configurazione per il container NGINX
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
      - mysql
    networks:
      - capri-network
