
nelmio_cors:
    paths:
        '^/': ~
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:5173']  # Aggiungi il dominio del frontend React
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        expose_headers: ['Link']
        max_age: 3600
